import type { KeywordData } from './types'

export const KEYWORDS_DB: Record<string, KeywordData> = {
  'Retain': {
    name: 'Retain',
    game: 'Slay the Spire',
    short_desc: 'Karta nie jest odrzucana na koniec tury — zostaje w ręce.',
    full_desc: 'Normalnie wszystkie karty w ręce są odrzucane do discard pile na końcu tury gracza. Karty z keyword Retain są wyjątkiem — pozostają w ręce do następnej tury. Po zagraniu trafiają normalnie do discard pile (chyba że mają też Exhaust). Runic Pyramid (relic) daje Retain wszystkim kartom.',
    examples: ['Miracle', 'Insight', 'Establishment', 'Windmill Strike'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Retain',
    verified: true,
  },
  'Exhaust': {
    name: 'Exhaust',
    game: 'Slay the Spire',
    short_desc: 'Karta jest usuwana z gry po zagraniu.',
    full_desc: 'Gdy karta z Exhaust zostaje zagrana, trafia do exhaust pile — specjalnej strefy usuniętych kart. Nie wraca do draw pile ani discard pile do końca walki. Jedynym sposobem odzyskania karty z exhaust pile jest karta Exhume. Dead Branch generuje losową kartę za każdy exhaust. Strange Spoon daje 50% szans że exhaust nie zadziała.',
    examples: ['Miracle', 'Apparition', 'Beta', 'Insight', 'Offering'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Exhaust',
    verified: true,
  },
  'Ethereal': {
    name: 'Ethereal',
    game: 'Slay the Spire',
    short_desc: 'Jeśli karta jest w ręce na koniec tury — zostaje automatycznie exhaustowana.',
    full_desc: 'Karty z keyword Ethereal muszą być zagrane lub odrzucone w turze, w której je mamy. Jeśli trzymamy je na koniec tury — zostają automatycznie exhaustowane (usunięte z gry). Retain NIE ratuje od Ethereal — karta z obu keywords i tak zostanie exhaustowana. Discard (np. Gambling Chip) zapobiega exhaustowi.',
    examples: ['Apparition', 'Carnage', 'Ghostly'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Ethereal',
    verified: true,
  },
  'Intangible': {
    name: 'Intangible',
    game: 'Slay the Spire',
    short_desc: 'Wszystkie obrażenia redukowane do 1 na czas działania.',
    full_desc: 'Intangible to buff (dla gracza) lub debuff (od wroga). Gdy postać ma Intangible, każdy oddzielny hit zadaje dokładnie 1 obrażenie zamiast normalnej wartości. Działa na KAŻDY hit osobno — multi-hit ataki (np. 5×3) zadają 1+1+1+1+1 = 5 zamiast 15. Jeden z najpotężniejszych efektów obronnych w grze.',
    examples: ['Apparition', 'Wraith Form'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Intangible',
    verified: true,
  },
  'Strength': {
    name: 'Strength',
    game: 'Slay the Spire',
    short_desc: 'Zwiększa obrażenia ataków o wartość Strength.',
    full_desc: 'Strength to buff który dodaje swoją wartość do obrażeń każdego ataku. Jeśli masz 3 Strength i grasz atak za 6, zadajesz 9. Działa na każdy hit multi-hitowych ataków osobno. Może być ujemny. Flex daje tymczasowy Strength (znika na koniec tury).',
    examples: ['J.A.X.', 'Inflame', 'Spot Weakness', 'Limit Break'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Strength',
    verified: true,
  },
  'Draw': {
    name: 'Draw',
    game: 'Slay the Spire',
    short_desc: 'Dobranie dodatkowych kart z draw pile.',
    full_desc: 'Efekt Draw pozwala dobrać określoną liczbę kart z draw pile. Standardowo gracz dobiera 5 kart na turę. Jeśli draw pile jest pusty, discard pile jest tasowany i staje się nowym draw pile. No Draw debuff blokuje dobieranie kart.',
    examples: ['Insight', 'Backflip', 'Pommel Strike', 'Battle Trance'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Draw',
    verified: true,
  },
  'X cost': {
    name: 'X cost',
    game: 'Slay the Spire',
    short_desc: 'Karta zużywa całą energię — efekt skaluje z wydaną energią.',
    full_desc: 'Karty z kosztem X zużywają całą dostępną energię gracza. Wartość X to ilość wydanej energii, a efekt skaluje proporcjonalnie. Chemical X (relic) daje +2 do X. Double Energy podwaja energię przed zagraniem X-cost karty.',
    examples: ['Expunger', 'Whirlwind', 'Malaise', 'Skewer'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/X',
    verified: true,
  },
  'Heal': {
    name: 'Heal',
    game: 'Slay the Spire',
    short_desc: 'Odzyskiwanie HP do maksymalnego poziomu.',
    full_desc: 'Heal przywraca utracone HP. Nie może przekroczyć Max HP. W walce heal jest rzadki. Mark of the Bloom (relic od bossa) blokuje WSZYSTKIE heale.',
    examples: ['Bite', 'Feed', 'Reaper', 'Self Repair'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Heal',
    verified: true,
  },
  // StS additional
  'Vulnerable': {
    name: 'Vulnerable', game: 'Slay the Spire',
    short_desc: 'Cel otrzymuje 50% więcej obrażeń z ataków.',
    full_desc: 'Vulnerable to debuff — cel otrzymuje 50% więcej obrażeń z ataków (zaokrąglane w górę). Trwa określoną liczbę tur. Nakładany przez Bash, Thunderclap, Uppercut.',
    examples: ['Bash', 'Thunderclap', 'Uppercut'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Vulnerable', verified: true,
  },
  'Weak': {
    name: 'Weak', game: 'Slay the Spire',
    short_desc: 'Cel zadaje 25% mniej obrażeń atakami.',
    full_desc: 'Weak to debuff — cel zadaje 25% mniej obrażeń atakami (zaokrąglane w dół). Trwa określoną liczbę tur.',
    examples: ['Neutralize', 'Leg Sweep'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Weak', verified: true,
  },
  'Frail': {
    name: 'Frail', game: 'Slay the Spire',
    short_desc: 'Cel zyskuje 25% mniej Block z kart.',
    full_desc: 'Frail to debuff — Block zyskiwany z kart jest redukowany o 25% (zaokrąglane w dół). Nie wpływa na Block z innych źródeł.',
    examples: ['Frail debuff from enemies'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Frail', verified: true,
  },
  'Innate': {
    name: 'Innate', game: 'Slay the Spire',
    short_desc: 'Karta jest zawsze w pierwszej ręce na początku walki.',
    full_desc: 'Karty z Innate są automatycznie dobierane do pierwszej ręki na początku walki, niezależnie od tasowania.',
    examples: ['Survivor+', 'Dramatic Entrance'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Innate', verified: true,
  },
  'Poison': {
    name: 'Poison', game: 'Slay the Spire',
    short_desc: 'Cel traci HP równe Poison na początku tury, potem Poison spada o 1.',
    full_desc: 'Poison to debuff — na początku tury cel traci HP równe stackowi Poison, potem stack spada o 1. Stackuje się nieskończenie. Główna mechanika klasy Silent.',
    examples: ['Deadly Poison', 'Noxious Fumes', 'Catalyst'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Poison', verified: true,
  },
  'Scry': {
    name: 'Scry', game: 'Slay the Spire',
    short_desc: 'Podgląd X kart z góry draw pile — odrzuć niechciane.',
    full_desc: 'Scry pozwala podejrzeć X kart z góry draw pile i odrzucić dowolne z nich. Mechanika Watchera do manipulacji draw pile.',
    examples: ['Third Eye', 'Cut Through Fate'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Scry', verified: true,
  },
  'Channel': {
    name: 'Channel', game: 'Slay the Spire',
    short_desc: 'Tworzenie Orba (Lightning/Frost/Dark/Plasma) w slotach Defecta.',
    full_desc: 'Channel tworzy Orb w wolnym slocie Defecta. Każdy Orb ma efekt pasywny (co turę) i evoke (gdy jest wyrzucany). Defect startuje z 3 slotami.',
    examples: ['Zap', 'Cold Snap', 'Glacier'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Channel', verified: true,
  },
  'Evoke': {
    name: 'Evoke', game: 'Slay the Spire',
    short_desc: 'Aktywacja mocy Orba i usunięcie go ze slota.',
    full_desc: 'Evoke wyrzuca najstarszego Orba — Lightning zadaje obrażenia, Frost daje Block, Dark zadaje obrażenia, Plasma daje Energy.',
    examples: ['Dualcast', 'Multi-Cast'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Evoke', verified: true,
  },
  'Focus': {
    name: 'Focus', game: 'Slay the Spire',
    short_desc: 'Wzmacnia pasywne efekty Orbów Defecta.',
    full_desc: 'Focus dodaje swoją wartość do pasywnych efektów orbów. +2 Focus = Lightning zadaje pasywnie +2, Frost daje +2 Block, etc.',
    examples: ['Defragment', 'Consume', 'Biased Cognition'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Focus', verified: true,
  },
  'Wrath': {
    name: 'Wrath', game: 'Slay the Spire',
    short_desc: 'Stance Watchera — podwójne obrażenia zadawane i otrzymywane.',
    full_desc: 'Wrath to stance w którym zadajesz 2x obrażenia ale też otrzymujesz 2x obrażenia. Ryzykowny ale potężny. Wyjście do Calm daje energię.',
    examples: ['Eruption', 'Tantrum'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Wrath', verified: true,
  },
  'Calm': {
    name: 'Calm', game: 'Slay the Spire',
    short_desc: 'Stance Watchera — opuszczenie daje 2 Energy.',
    full_desc: 'Calm to defensywny stance. Brak bonusów w Calm, ale OPUSZCZENIE Calm (przejście do innego stance) daje 2 Energy. Kluczowy do energy generation.',
    examples: ['Empty Mind', 'Inner Peace'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Calm', verified: true,
  },
  'Mantra': {
    name: 'Mantra', game: 'Slay the Spire',
    short_desc: 'Po zebraniu 10 Mantry, Watcher wchodzi w Divinity.',
    full_desc: 'Mantra stackuje się. Po osiągnięciu 10, Watcher wchodzi w stance Divinity (3x obrażenia + 3 Energy). Mantra powyżej 10 przenosi się.',
    examples: ['Devotion', 'Worship'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Mantra', verified: true,
  },
  // Monster Train
  'Consume': {
    name: 'Consume', game: 'Monster Train',
    short_desc: 'Karta jest usuwana po zagraniu — jednorazowe użycie.',
    full_desc: 'Spelle z Consume mogą być zagrane tylko raz na bitwę. Po zagraniu znikają. Odpowiednik Exhaust ze StS.',
    examples: ['Imp-in-a-Box', 'Rage Serum'], wiki_url: 'https://monster-train.fandom.com/wiki/Consume', verified: true,
  },
  'Armor': {
    name: 'Armor', game: 'Monster Train',
    short_desc: 'Absorbuje obrażenia zanim trafią w HP.',
    full_desc: 'Armor daje trwałą tarczę — nie znika na koniec tury. Każdy punkt absorbuje 1 punkt obrażeń.',
    examples: ['Fortify'], wiki_url: 'https://monster-train.fandom.com/wiki/Armor', verified: true,
  },
  'Rage': {
    name: 'Rage', game: 'Monster Train',
    short_desc: 'Zwiększa atak jednostki.',
    full_desc: 'Rage = +Attack buff. Stacks. Odpowiednik Strength ze StS.',
    examples: ['Dark Deal', 'Rage Serum'], wiki_url: 'https://monster-train.fandom.com/wiki/Rage', verified: true,
  },
  'Sweep': {
    name: 'Sweep', game: 'Monster Train',
    short_desc: 'Atak trafia wszystkie wrogie jednostki na piętrze.',
    full_desc: 'Sweep sprawia że atak trafia ALL wrogów na piętrze, nie tylko unit z przodu.',
    examples: ['Sweep units'], wiki_url: 'https://monster-train.fandom.com/wiki/Sweep', verified: true,
  },
  'Lifesteal': {
    name: 'Lifesteal', game: 'Monster Train',
    short_desc: 'Leczy Pyra za obrażenia zadane wrogom.',
    full_desc: 'Lifesteal leczy twojego Pyra (pyre HP) za obrażenia zadane przez tę jednostkę.',
    examples: ['Umbra units'], wiki_url: 'https://monster-train.fandom.com/wiki/Lifesteal', verified: true,
  },
  'Multistrike': {
    name: 'Multistrike', game: 'Monster Train',
    short_desc: 'Jednostka atakuje wielokrotnie.',
    full_desc: 'Multistrike N = N+1 łącznych ataków. Stacks.',
    examples: ['Champions with Multistrike'], wiki_url: 'https://monster-train.fandom.com/wiki/Multistrike', verified: true,
  },
  'Gorge': {
    name: 'Gorge', game: 'Monster Train',
    short_desc: 'Efekt triggerowany przez zjadanie Morseli.',
    full_desc: 'Gorge triggeruje się gdy jednostka "zje" Morsela. Mechanika klanu Umbra — Morsele to małe units-jedzenie.',
    examples: ['Umbra Gorge units'], wiki_url: 'https://monster-train.fandom.com/wiki/Gorge', verified: true,
  },
  'Incant': {
    name: 'Incant', game: 'Monster Train',
    short_desc: 'Efekt triggerowany przy graniu spelli.',
    full_desc: 'Incant triggeruje się za każdym razem gdy gracz zagra spell. Efekt jest per-unit.',
    examples: ['Incant units'], wiki_url: 'https://monster-train.fandom.com/wiki/Incant', verified: true,
  },
  // Wildfrost
  'Ink': {
    name: 'Ink', game: 'Wildfrost',
    short_desc: 'Spowalnia counter wroga.',
    full_desc: 'Ink dodaje do countera wroga — opóźnia jego następny atak.',
    examples: ['Binku'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Ink', verified: true,
  },
  'Snow': {
    name: 'Snow', game: 'Wildfrost',
    short_desc: 'Dodaje do countera, opóźniając akcję.',
    full_desc: 'Snow to główny debuff kontrolny w Wildfrost. Zwiększa counter wroga.',
    examples: ['Snowdwell companions'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Snow', verified: true,
  },
  'Shell': {
    name: 'Shell', game: 'Wildfrost',
    short_desc: 'Tarcza absorbująca obrażenia.',
    full_desc: 'Shell to tymczasowy shield. Absorbuje obrażenia.',
    examples: ['Shell companions'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Shell', verified: true,
  },
  'Teeth': {
    name: 'Teeth', game: 'Wildfrost',
    short_desc: 'Zadaje obrażenia atakującemu (thorns).',
    full_desc: 'Teeth zadaje obrażenia atakującemu = wartość Teeth. Odpowiednik Thorns ze StS.',
    examples: ['Teeth cards'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Teeth', verified: true,
  },
  'Spice': {
    name: 'Spice', game: 'Wildfrost',
    short_desc: 'Tymczasowy boost do ataku.',
    full_desc: 'Spice dodaje tymczasowy Attack do karty. Zużywany po ataku.',
    examples: ['Spice companions'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Spice', verified: true,
  },
  'Frenzy': {
    name: 'Frenzy', game: 'Wildfrost',
    short_desc: 'Wielokrotne ataki na trigger.',
    full_desc: 'Frenzy X = X+1 ataków. Odpowiednik Multistrike z Monster Train.',
    examples: ['Frenzy companions'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Frenzy', verified: true,
  },
  'Barrage': {
    name: 'Barrage', game: 'Wildfrost',
    short_desc: 'Atak trafia wszystkich wrogów.',
    full_desc: 'Barrage sprawia że atak trafia ALL wrogów. Odpowiednik Sweep z MT.',
    examples: ['Barrage companions'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Barrage', verified: true,
  },
}
