import type { KeywordData } from './types'

export const KEYWORDS_DB: Record<string, KeywordData> = {
  'Retain': {
    name: 'Retain',
    game: 'Slay the Spire',
    short_desc: 'Karta nie jest odrzucana na koniec tury — zostaje w ręce.',
    full_desc: 'Normalnie wszystkie karty w ręce są odrzucane do discard pile na końcu tury gracza. Karty z keyword Retain są wyjątkiem — pozostają w ręce do następnej tury. Po zagraniu trafiają normalnie do discard pile (chyba że mają też Exhaust). Runic Pyramid (relic) daje Retain wszystkim kartom.',
    examples: ['Miracle', 'Insight', 'Establishment', 'Windmill Strike'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Retain',
    verified: true,
  },
  'Exhaust': {
    name: 'Exhaust',
    game: 'Slay the Spire',
    short_desc: 'Karta jest usuwana z gry po zagraniu.',
    full_desc: 'Gdy karta z Exhaust zostaje zagrana, trafia do exhaust pile — specjalnej strefy usuniętych kart. Nie wraca do draw pile ani discard pile do końca walki. Jedynym sposobem odzyskania karty z exhaust pile jest karta Exhume. Dead Branch generuje losową kartę za każdy exhaust. Strange Spoon daje 50% szans że exhaust nie zadziała.',
    examples: ['Miracle', 'Apparition', 'Beta', 'Insight', 'Offering'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Exhaust',
    verified: true,
  },
  'Ethereal': {
    name: 'Ethereal',
    game: 'Slay the Spire',
    short_desc: 'Jeśli karta jest w ręce na koniec tury — zostaje automatycznie exhaustowana.',
    full_desc: 'Karty z keyword Ethereal muszą być zagrane lub odrzucone w turze, w której je mamy. Jeśli trzymamy je na koniec tury — zostają automatycznie exhaustowane (usunięte z gry). Retain NIE ratuje od Ethereal — karta z obu keywords i tak zostanie exhaustowana. Discard (np. Gambling Chip) zapobiega exhaustowi.',
    examples: ['Apparition', 'Carnage', 'Ghostly'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Ethereal',
    verified: true,
  },
  'Intangible': {
    name: 'Intangible',
    game: 'Slay the Spire',
    short_desc: 'Wszystkie obrażenia redukowane do 1 na czas działania.',
    full_desc: 'Intangible to buff (dla gracza) lub debuff (od wroga). Gdy postać ma Intangible, każdy oddzielny hit zadaje dokładnie 1 obrażenie zamiast normalnej wartości. Działa na KAŻDY hit osobno — multi-hit ataki (np. 5×3) zadają 1+1+1+1+1 = 5 zamiast 15. Jeden z najpotężniejszych efektów obronnych w grze.',
    examples: ['Apparition', 'Wraith Form'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Intangible',
    verified: true,
  },
  'Strength': {
    name: 'Strength',
    game: 'Slay the Spire',
    short_desc: 'Zwiększa obrażenia ataków o wartość Strength.',
    full_desc: 'Strength to buff który dodaje swoją wartość do obrażeń każdego ataku. Jeśli masz 3 Strength i grasz atak za 6, zadajesz 9. Działa na każdy hit multi-hitowych ataków osobno. Może być ujemny. Flex daje tymczasowy Strength (znika na koniec tury).',
    examples: ['J.A.X.', 'Inflame', 'Spot Weakness', 'Limit Break'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Strength',
    verified: true,
  },
  'Draw': {
    name: 'Draw',
    game: 'Slay the Spire',
    short_desc: 'Dobranie dodatkowych kart z draw pile.',
    full_desc: 'Efekt Draw pozwala dobrać określoną liczbę kart z draw pile. Standardowo gracz dobiera 5 kart na turę. Jeśli draw pile jest pusty, discard pile jest tasowany i staje się nowym draw pile. No Draw debuff blokuje dobieranie kart.',
    examples: ['Insight', 'Backflip', 'Pommel Strike', 'Battle Trance'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Draw',
    verified: true,
  },
  'X cost': {
    name: 'X cost',
    game: 'Slay the Spire',
    short_desc: 'Karta zużywa całą energię — efekt skaluje z wydaną energią.',
    full_desc: 'Karty z kosztem X zużywają całą dostępną energię gracza. Wartość X to ilość wydanej energii, a efekt skaluje proporcjonalnie. Chemical X (relic) daje +2 do X. Double Energy podwaja energię przed zagraniem X-cost karty.',
    examples: ['Expunger', 'Whirlwind', 'Malaise', 'Skewer'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/X',
    verified: true,
  },
  'Heal': {
    name: 'Heal',
    game: 'Slay the Spire',
    short_desc: 'Odzyskiwanie HP do maksymalnego poziomu.',
    full_desc: 'Heal przywraca utracone HP. Nie może przekroczyć Max HP. W walce heal jest rzadki. Mark of the Bloom (relic od bossa) blokuje WSZYSTKIE heale.',
    examples: ['Bite', 'Feed', 'Reaper', 'Self Repair'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Heal',
    verified: true,
  },
}
