import type { KeywordData } from './types'

export const KEYWORDS_DB: Record<string, KeywordData> = {
  'Retain': {
    name: 'Retain',
    game: 'Slay the Spire',
    short_desc: 'Karta nie jest odrzucana na koniec tury — zostaje w ręce.',
    full_desc: 'Normalnie wszystkie karty w ręce są odrzucane do discard pile na końcu tury gracza. Karty z keyword Retain są wyjątkiem — pozostają w ręce do następnej tury. Po zagraniu trafiają normalnie do discard pile (chyba że mają też Exhaust). Runic Pyramid (relic) daje Retain wszystkim kartom.',
    examples: ['Miracle', 'Insight', 'Establishment', 'Windmill Strike'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Retain',
    verified: true,
  },
  'Exhaust': {
    name: 'Exhaust',
    game: 'Slay the Spire',
    short_desc: 'Karta jest usuwana z gry po zagraniu.',
    full_desc: 'Gdy karta z Exhaust zostaje zagrana, trafia do exhaust pile — specjalnej strefy usuniętych kart. Nie wraca do draw pile ani discard pile do końca walki. Jedynym sposobem odzyskania karty z exhaust pile jest karta Exhume. Dead Branch generuje losową kartę za każdy exhaust. Strange Spoon daje 50% szans że exhaust nie zadziała.',
    examples: ['Miracle', 'Apparition', 'Beta', 'Insight', 'Offering'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Exhaust',
    verified: true,
  },
  'Ethereal': {
    name: 'Ethereal',
    game: 'Slay the Spire',
    short_desc: 'Jeśli karta jest w ręce na koniec tury — zostaje automatycznie exhaustowana.',
    full_desc: 'Karty z keyword Ethereal muszą być zagrane lub odrzucone w turze, w której je mamy. Jeśli trzymamy je na koniec tury — zostają automatycznie exhaustowane (usunięte z gry). Retain NIE ratuje od Ethereal — karta z obu keywords i tak zostanie exhaustowana. Discard (np. Gambling Chip) zapobiega exhaustowi.',
    examples: ['Apparition', 'Carnage', 'Ghostly'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Ethereal',
    verified: true,
  },
  'Intangible': {
    name: 'Intangible',
    game: 'Slay the Spire',
    short_desc: 'Wszystkie obrażenia redukowane do 1 na czas działania.',
    full_desc: 'Intangible to buff (dla gracza) lub debuff (od wroga). Gdy postać ma Intangible, każdy oddzielny hit zadaje dokładnie 1 obrażenie zamiast normalnej wartości. Działa na KAŻDY hit osobno — multi-hit ataki (np. 5×3) zadają 1+1+1+1+1 = 5 zamiast 15. Jeden z najpotężniejszych efektów obronnych w grze.',
    examples: ['Apparition', 'Wraith Form'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Intangible',
    verified: true,
  },
  'Strength': {
    name: 'Strength',
    game: 'Slay the Spire',
    short_desc: 'Zwiększa obrażenia ataków o wartość Strength.',
    full_desc: 'Strength to buff który dodaje swoją wartość do obrażeń każdego ataku. Jeśli masz 3 Strength i grasz atak za 6, zadajesz 9. Działa na każdy hit multi-hitowych ataków osobno. Może być ujemny. Flex daje tymczasowy Strength (znika na koniec tury).',
    examples: ['J.A.X.', 'Inflame', 'Spot Weakness', 'Limit Break'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Strength',
    verified: true,
  },
  'Draw': {
    name: 'Draw',
    game: 'Slay the Spire',
    short_desc: 'Dobranie dodatkowych kart z draw pile.',
    full_desc: 'Efekt Draw pozwala dobrać określoną liczbę kart z draw pile. Standardowo gracz dobiera 5 kart na turę. Jeśli draw pile jest pusty, discard pile jest tasowany i staje się nowym draw pile. No Draw debuff blokuje dobieranie kart.',
    examples: ['Insight', 'Backflip', 'Pommel Strike', 'Battle Trance'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Draw',
    verified: true,
  },
  'X cost': {
    name: 'X cost',
    game: 'Slay the Spire',
    short_desc: 'Karta zużywa całą energię — efekt skaluje z wydaną energią.',
    full_desc: 'Karty z kosztem X zużywają całą dostępną energię gracza. Wartość X to ilość wydanej energii, a efekt skaluje proporcjonalnie. Chemical X (relic) daje +2 do X. Double Energy podwaja energię przed zagraniem X-cost karty.',
    examples: ['Expunger', 'Whirlwind', 'Malaise', 'Skewer'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/X',
    verified: true,
  },
  'Heal': {
    name: 'Heal',
    game: 'Slay the Spire',
    short_desc: 'Odzyskiwanie HP do maksymalnego poziomu.',
    full_desc: 'Heal przywraca utracone HP. Nie może przekroczyć Max HP. W walce heal jest rzadki. Mark of the Bloom (relic od bossa) blokuje WSZYSTKIE heale.',
    examples: ['Bite', 'Feed', 'Reaper', 'Self Repair'],
    wiki_url: 'https://slay-the-spire.fandom.com/wiki/Heal',
    verified: true,
  },
  // StS additional
  'Vulnerable': {
    name: 'Vulnerable', game: 'Slay the Spire',
    short_desc: 'Cel otrzymuje 50% więcej obrażeń z ataków.',
    full_desc: 'Vulnerable to debuff — cel otrzymuje 50% więcej obrażeń z ataków (zaokrąglane w górę). Trwa określoną liczbę tur. Nakładany przez Bash, Thunderclap, Uppercut.',
    examples: ['Bash', 'Thunderclap', 'Uppercut'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Vulnerable', verified: true,
  },
  'Weak': {
    name: 'Weak', game: 'Slay the Spire',
    short_desc: 'Cel zadaje 25% mniej obrażeń atakami.',
    full_desc: 'Weak to debuff — cel zadaje 25% mniej obrażeń atakami (zaokrąglane w dół). Trwa określoną liczbę tur.',
    examples: ['Neutralize', 'Leg Sweep'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Weak', verified: true,
  },
  'Frail': {
    name: 'Frail', game: 'Slay the Spire',
    short_desc: 'Cel zyskuje 25% mniej Block z kart.',
    full_desc: 'Frail to debuff — Block zyskiwany z kart jest redukowany o 25% (zaokrąglane w dół). Nie wpływa na Block z innych źródeł.',
    examples: ['Frail debuff from enemies'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Frail', verified: true,
  },
  'Innate': {
    name: 'Innate', game: 'Slay the Spire',
    short_desc: 'Karta jest zawsze w pierwszej ręce na początku walki.',
    full_desc: 'Karty z Innate są automatycznie dobierane do pierwszej ręki na początku walki, niezależnie od tasowania.',
    examples: ['Survivor+', 'Dramatic Entrance'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Innate', verified: true,
  },
  'Poison': {
    name: 'Poison', game: 'Slay the Spire',
    short_desc: 'Cel traci HP równe Poison na początku tury, potem Poison spada o 1.',
    full_desc: 'Poison to debuff — na początku tury cel traci HP równe stackowi Poison, potem stack spada o 1. Stackuje się nieskończenie. Główna mechanika klasy Silent.',
    examples: ['Deadly Poison', 'Noxious Fumes', 'Catalyst'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Poison', verified: true,
  },
  'Scry': {
    name: 'Scry', game: 'Slay the Spire',
    short_desc: 'Podgląd X kart z góry draw pile — odrzuć niechciane.',
    full_desc: 'Scry pozwala podejrzeć X kart z góry draw pile i odrzucić dowolne z nich. Mechanika Watchera do manipulacji draw pile.',
    examples: ['Third Eye', 'Cut Through Fate'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Scry', verified: true,
  },
  'Channel': {
    name: 'Channel', game: 'Slay the Spire',
    short_desc: 'Tworzenie Orba (Lightning/Frost/Dark/Plasma) w slotach Defecta.',
    full_desc: 'Channel tworzy Orb w wolnym slocie Defecta. Każdy Orb ma efekt pasywny (co turę) i evoke (gdy jest wyrzucany). Defect startuje z 3 slotami.',
    examples: ['Zap', 'Cold Snap', 'Glacier'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Channel', verified: true,
  },
  'Evoke': {
    name: 'Evoke', game: 'Slay the Spire',
    short_desc: 'Aktywacja mocy Orba i usunięcie go ze slota.',
    full_desc: 'Evoke wyrzuca najstarszego Orba — Lightning zadaje obrażenia, Frost daje Block, Dark zadaje obrażenia, Plasma daje Energy.',
    examples: ['Dualcast', 'Multi-Cast'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Evoke', verified: true,
  },
  'Focus': {
    name: 'Focus', game: 'Slay the Spire',
    short_desc: 'Wzmacnia pasywne efekty Orbów Defecta.',
    full_desc: 'Focus dodaje swoją wartość do pasywnych efektów orbów. +2 Focus = Lightning zadaje pasywnie +2, Frost daje +2 Block, etc.',
    examples: ['Defragment', 'Consume', 'Biased Cognition'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Focus', verified: true,
  },
  'Wrath': {
    name: 'Wrath', game: 'Slay the Spire',
    short_desc: 'Stance Watchera — podwójne obrażenia zadawane i otrzymywane.',
    full_desc: 'Wrath to stance w którym zadajesz 2x obrażenia ale też otrzymujesz 2x obrażenia. Ryzykowny ale potężny. Wyjście do Calm daje energię.',
    examples: ['Eruption', 'Tantrum'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Wrath', verified: true,
  },
  'Calm': {
    name: 'Calm', game: 'Slay the Spire',
    short_desc: 'Stance Watchera — opuszczenie daje 2 Energy.',
    full_desc: 'Calm to defensywny stance. Brak bonusów w Calm, ale OPUSZCZENIE Calm (przejście do innego stance) daje 2 Energy. Kluczowy do energy generation.',
    examples: ['Empty Mind', 'Inner Peace'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Calm', verified: true,
  },
  'Mantra': {
    name: 'Mantra', game: 'Slay the Spire',
    short_desc: 'Po zebraniu 10 Mantry, Watcher wchodzi w Divinity.',
    full_desc: 'Mantra stackuje się. Po osiągnięciu 10, Watcher wchodzi w stance Divinity (3x obrażenia + 3 Energy). Mantra powyżej 10 przenosi się.',
    examples: ['Devotion', 'Worship'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Mantra', verified: true,
  },
  // Monster Train
  'Consume': {
    name: 'Consume', game: 'Monster Train',
    short_desc: 'Karta jest usuwana po zagraniu — jednorazowe użycie.',
    full_desc: 'Spelle z Consume mogą być zagrane tylko raz na bitwę. Po zagraniu znikają. Odpowiednik Exhaust ze StS.',
    examples: ['Imp-in-a-Box', 'Rage Serum'], wiki_url: 'https://monster-train.fandom.com/wiki/Consume', verified: true,
  },
  'Armor': {
    name: 'Armor', game: 'Monster Train',
    short_desc: 'Absorbuje obrażenia zanim trafią w HP.',
    full_desc: 'Armor daje trwałą tarczę — nie znika na koniec tury. Każdy punkt absorbuje 1 punkt obrażeń.',
    examples: ['Fortify'], wiki_url: 'https://monster-train.fandom.com/wiki/Armor', verified: true,
  },
  'Rage': {
    name: 'Rage', game: 'Monster Train',
    short_desc: 'Zwiększa atak jednostki.',
    full_desc: 'Rage = +Attack buff. Stacks. Odpowiednik Strength ze StS.',
    examples: ['Dark Deal', 'Rage Serum'], wiki_url: 'https://monster-train.fandom.com/wiki/Rage', verified: true,
  },
  'Sweep': {
    name: 'Sweep', game: 'Monster Train',
    short_desc: 'Atak trafia wszystkie wrogie jednostki na piętrze.',
    full_desc: 'Sweep sprawia że atak trafia ALL wrogów na piętrze, nie tylko unit z przodu.',
    examples: ['Sweep units'], wiki_url: 'https://monster-train.fandom.com/wiki/Sweep', verified: true,
  },
  'Lifesteal': {
    name: 'Lifesteal', game: 'Monster Train',
    short_desc: 'Leczy Pyra za obrażenia zadane wrogom.',
    full_desc: 'Lifesteal leczy twojego Pyra (pyre HP) za obrażenia zadane przez tę jednostkę.',
    examples: ['Umbra units'], wiki_url: 'https://monster-train.fandom.com/wiki/Lifesteal', verified: true,
  },
  'Multistrike': {
    name: 'Multistrike', game: 'Monster Train',
    short_desc: 'Jednostka atakuje wielokrotnie.',
    full_desc: 'Multistrike N = N+1 łącznych ataków. Stacks.',
    examples: ['Champions with Multistrike'], wiki_url: 'https://monster-train.fandom.com/wiki/Multistrike', verified: true,
  },
  'Gorge': {
    name: 'Gorge', game: 'Monster Train',
    short_desc: 'Efekt triggerowany przez zjadanie Morseli.',
    full_desc: 'Gorge triggeruje się gdy jednostka "zje" Morsela. Mechanika klanu Umbra — Morsele to małe units-jedzenie.',
    examples: ['Umbra Gorge units'], wiki_url: 'https://monster-train.fandom.com/wiki/Gorge', verified: true,
  },
  'Incant': {
    name: 'Incant', game: 'Monster Train',
    short_desc: 'Efekt triggerowany przy graniu spelli.',
    full_desc: 'Incant triggeruje się za każdym razem gdy gracz zagra spell. Efekt jest per-unit.',
    examples: ['Incant units'], wiki_url: 'https://monster-train.fandom.com/wiki/Incant', verified: true,
  },
  // Wildfrost
  'Ink': {
    name: 'Ink', game: 'Wildfrost',
    short_desc: 'Spowalnia counter wroga.',
    full_desc: 'Ink dodaje do countera wroga — opóźnia jego następny atak.',
    examples: ['Binku'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Ink', verified: true,
  },
  'Snow': {
    name: 'Snow', game: 'Wildfrost',
    short_desc: 'Dodaje do countera, opóźniając akcję.',
    full_desc: 'Snow to główny debuff kontrolny w Wildfrost. Zwiększa counter wroga.',
    examples: ['Snowdwell companions'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Snow', verified: true,
  },
  'Shell': {
    name: 'Shell', game: 'Wildfrost',
    short_desc: 'Tarcza absorbująca obrażenia.',
    full_desc: 'Shell to tymczasowy shield. Absorbuje obrażenia.',
    examples: ['Shell companions'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Shell', verified: true,
  },
  'Teeth': {
    name: 'Teeth', game: 'Wildfrost',
    short_desc: 'Zadaje obrażenia atakującemu (thorns).',
    full_desc: 'Teeth zadaje obrażenia atakującemu = wartość Teeth. Odpowiednik Thorns ze StS.',
    examples: ['Teeth cards'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Teeth', verified: true,
  },
  'Spice': {
    name: 'Spice', game: 'Wildfrost',
    short_desc: 'Tymczasowy boost do ataku.',
    full_desc: 'Spice dodaje tymczasowy Attack do karty. Zużywany po ataku.',
    examples: ['Spice companions'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Spice', verified: true,
  },
  'Frenzy': {
    name: 'Frenzy', game: 'Wildfrost',
    short_desc: 'Wielokrotne ataki na trigger.',
    full_desc: 'Frenzy X = X+1 ataków. Odpowiednik Multistrike z Monster Train.',
    examples: ['Frenzy companions'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Frenzy', verified: true,
  },
  'Barrage': {
    name: 'Barrage', game: 'Wildfrost',
    short_desc: 'Atak trafia wszystkich wrogów.',
    full_desc: 'Barrage sprawia że atak trafia ALL wrogów. Odpowiednik Sweep z MT.',
    examples: ['Barrage companions'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Barrage', verified: true,
  },
  // ── StS MISSING ──
  'Block': {
    name: 'Block', game: 'Slay the Spire',
    short_desc: 'Tymczasowa tarcza absorbująca obrażenia, znika na początku następnej tury.',
    full_desc: 'Block to podstawowy mechanizm obronny. Absorbuje obrażenia punkt za punkt. Znika na początku tury gracza (chyba że Barricade jest aktywne). Zyskiwany przez karty typu Defend, Shrug It Off, itp.',
    examples: ['Defend', 'Shrug It Off', 'Impervious', 'Leap'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Block', verified: true,
  },
  'Burn': {
    name: 'Burn', game: 'Slay the Spire',
    short_desc: 'Status karta — Unplayable, na koniec tury zadaje 2 obrażenia graczowi.',
    full_desc: 'Burn to karta statusowa dodawana do talii przez wrogów. Jest Unplayable — nie można jej zagrać. Na koniec tury, jeśli jest w ręce, zadaje 2 obrażenia. Jedyny sposób pozbycia się to Exhaust.',
    examples: ['Burn (status card)', 'Immolate adds Burns'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Burn', verified: true,
  },
  'Dazed': {
    name: 'Dazed', game: 'Slay the Spire',
    short_desc: 'Status karta — Unplayable + Ethereal.',
    full_desc: 'Dazed to karta statusowa. Jest Unplayable (nie można zagrać) i Ethereal (na koniec tury zostaje exhaustowana). Dodawana do draw pile przez wrogów jak Donu & Deca. Zatyka rękę na jedną turę.',
    examples: ['Dazed (status card)'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Dazed', verified: true,
  },
  'Dexterity': {
    name: 'Dexterity', game: 'Slay the Spire',
    short_desc: 'Dodaje swoją wartość do Block zyskiwanego z kart.',
    full_desc: 'Dexterity to buff zwiększający Block. Jeśli masz +3 Dexterity i grasz kartę dającą 5 Block, zyskujesz 8 Block. Działa na każdą kartę dającą Block. Może być ujemny (debuff).',
    examples: ['Footwork', 'Dodge and Roll'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Dexterity', verified: true,
  },
  'Discard': {
    name: 'Discard', game: 'Slay the Spire',
    short_desc: 'Odrzucenie karty z ręki do discard pile.',
    full_desc: 'Discard przenosi kartę z ręki do discard pile. Różne od Exhaust — karta wraca po przetasowaniu. Karty jak Tactician i Reflex triggerują efekty gdy są odrzucone.',
    examples: ['Prepared', 'Acrobatics', 'Gambling Chip'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Discard', verified: true,
  },
  'Divinity': {
    name: 'Divinity', game: 'Slay the Spire',
    short_desc: 'Stance Watchera — 3x obrażenia + 3 dodatkowej Energy.',
    full_desc: 'Divinity to najsilniejszy stance Watchera. Zadajesz 3x obrażeń i zyskujesz 3 dodatkowej Energy. Wchodzisz w Divinity po zebraniu 10 Mantry. Trwa tylko jedną turę — po niej automatycznie wracasz do Neutral.',
    examples: ['Devotion', 'Worship'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Divinity', verified: true,
  },
  'Frost': {
    name: 'Frost', game: 'Slay the Spire',
    short_desc: 'Orb Defecta — pasywnie daje Block, evoke daje więcej Block.',
    full_desc: 'Frost to typ Orba dla Defecta. Efekt pasywny: zyskujesz 2+Focus Block na koniec tury. Evoke: zyskujesz 5+Focus Block natychmiast. Główny Orb defensywny.',
    examples: ['Coolheaded', 'Glacier', 'Cold Snap'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Frost', verified: true,
  },
  'Lightning': {
    name: 'Lightning', game: 'Slay the Spire',
    short_desc: 'Orb Defecta — pasywnie zadaje obrażenia, evoke zadaje więcej.',
    full_desc: 'Lightning to typ Orba dla Defecta. Efekt pasywny: zadaje 3+Focus obrażeń losowemu wrogowi na koniec tury. Evoke: zadaje 8+Focus obrażeń losowemu wrogowi natychmiast.',
    examples: ['Zap', 'Ball Lightning', 'Electrodynamics'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Lightning', verified: true,
  },
  'Orb': {
    name: 'Orb', game: 'Slay the Spire',
    short_desc: 'Magiczne sfery Defecta z pasywnymi efektami i evoke.',
    full_desc: 'Orby to mechanika Defecta. Channelowane do slotów (domyślnie 3). Każdy Orb ma efekt pasywny (co turę) i efekt evoke (gdy jest wyrzucany). Typy: Lightning, Frost, Dark, Plasma.',
    examples: ['Zap', 'Dualcast', 'Multi-Cast'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Orb', verified: true,
  },
  'Plasma': {
    name: 'Plasma', game: 'Slay the Spire',
    short_desc: 'Orb Defecta — pasywnie daje 1 Energy, evoke daje 2 Energy.',
    full_desc: 'Plasma to typ Orba dla Defecta. Efekt pasywny: zyskujesz 1 Energy na koniec tury. Evoke: zyskujesz 2 Energy natychmiast. Najrzadszy i najpotężniejszy Orb — energy generation.',
    examples: ['Fusion', 'Rainbow', 'Meteor Strike'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Plasma', verified: true,
  },
  'Shiv': {
    name: 'Shiv', game: 'Slay the Spire',
    short_desc: 'Generowana karta 0-cost: zadaje 4 obrażeń, Exhaust.',
    full_desc: 'Shiv to generowana karta ataku za 0 Energy. Zadaje 4 obrażeń (6 po ulepszeniu Accuracy). Exhaust po zagraniu. Generowana przez Blade Dance, Cloak and Dagger, Infinite Blades. Synergizuje z After Image, A Thousand Cuts.',
    examples: ['Blade Dance', 'Cloak and Dagger', 'Infinite Blades'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Shiv', verified: true,
  },
  'Unplayable': {
    name: 'Unplayable', game: 'Slay the Spire',
    short_desc: 'Karta nie może być zagrana — zatyka rękę.',
    full_desc: 'Karty z Unplayable nie mogą być zagrane z ręki. Jedyny sposób pozbycia się to Exhaust, Discard, lub specjalne efekty. Przykłady: Burn, Wound, Dazed, Slimed, Normality, Ascender\'s Bane.',
    examples: ['Burn', 'Wound', 'Dazed', 'Normality'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Unplayable', verified: true,
  },
  'Upgrade': {
    name: 'Upgrade', game: 'Slay the Spire',
    short_desc: 'Ulepszenie karty — silniejszy efekt na stałe.',
    full_desc: 'Upgrade wzmacnia kartę na stałe — zwykle lepsze wartości, niższy koszt, lub dodatkowy efekt. Można ulepszać na campfire (Rest Site) lub kartami jak Apotheosis i Armaments.',
    examples: ['Apotheosis', 'Armaments', 'Lesson Learned'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Upgrade', verified: true,
  },
  'Wound': {
    name: 'Wound', game: 'Slay the Spire',
    short_desc: 'Status karta — Unplayable, zatyka rękę.',
    full_desc: 'Wound to karta statusowa dodawana do talii przez wrogów i niektóre karty (Power Through, Reckless Charge). Jest Unplayable — nie robi nic, tylko zajmuje miejsce w ręce.',
    examples: ['Wound (status)', 'Power Through adds Wounds'], wiki_url: 'https://slay-the-spire.fandom.com/wiki/Wound', verified: true,
  },
  // ── MT MISSING ──
  'Ascend': {
    name: 'Ascend', game: 'Monster Train',
    short_desc: 'Przenosi jednostkę o jedno piętro wyżej.',
    full_desc: 'Ascend przesuwa jednostkę o jedno piętro wyżej na pociągu. Użyteczne do repozycjonowania unitów. Przeciwieństwo Descend.',
    examples: ['Hidden Passage', 'Gravity'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Card_Effects', verified: true,
  },
  'Burnout': {
    name: 'Burnout', game: 'Monster Train',
    short_desc: 'Jednostka jest niszczona po X turach.',
    full_desc: 'Burnout X oznacza że jednostka zginie po X turach. Counter zmniejsza się o 1 co turę. Gdy dotrze do 0 — unit umiera. Kluczowa mechanika Melting Remnant — ich units są silne ale mają Burnout. Synergizuje z Reform.',
    examples: ['Paraffin Thug', 'Wickless Baron', 'Boneshine'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Burnout', verified: true,
  },
  'Daze': {
    name: 'Daze', game: 'Monster Train',
    short_desc: 'Debuff zmniejszający atak jednostki.',
    full_desc: 'Daze to debuff redukujący Attack jednostki o podaną wartość. Stackuje się. Przeciwieństwo Rage.',
    examples: ['Deranged Brute', 'Wilting Sapwood'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Daze', verified: true,
  },
  'Damage Shield': {
    name: 'Damage Shield', game: 'Monster Train',
    short_desc: 'Absorbuje jedną instancję obrażeń całkowicie.',
    full_desc: 'Damage Shield chroni jednostkę przed jedną instancją obrażeń — niezależnie od wartości. Po absorpcji jednego hitu znika. Stackuje się — Damage Shield 2 = 2 hity zaabsorbowane.',
    examples: ['Morsel Jeweler', 'Guardian Stone'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Damage_Shield', verified: true,
  },
  'Descend': {
    name: 'Descend', game: 'Monster Train',
    short_desc: 'Przenosi jednostkę o jedno piętro niżej.',
    full_desc: 'Descend przesuwa jednostkę o jedno piętro niżej na pociągu. Przeciwieństwo Ascend.',
    examples: ['Descend spells'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Card_Effects', verified: true,
  },
  'Eaten': {
    name: 'Eaten', game: 'Monster Train',
    short_desc: 'Morsel został zjedzony — triggeruje efekt Gorge.',
    full_desc: 'Eaten oznacza że Morsel został zjedzony przez jednostkę z Gorge. Morsel jest zniszczony a jednostka z Gorge zyskuje swój bonus.',
    examples: ['Morsel units'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Gorge', verified: true,
  },
  'Endless': {
    name: 'Endless', game: 'Monster Train',
    short_desc: 'Jednostka wraca do ręki po śmierci.',
    full_desc: 'Jednostka z Endless nie jest usuwana po śmierci — wraca do ręki gracza. Można ją ponownie zagrać. Stackuje się z Burnout — unit z Burnout + Endless umiera od Burnout ale wraca do ręki.',
    examples: ['Bone Rattler', 'Endless units'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Endless', verified: true,
  },
  'Frostbite': {
    name: 'Frostbite', game: 'Monster Train',
    short_desc: 'Debuff zadający obrażenia na początku tury.',
    full_desc: 'Frostbite X zadaje X obrażeń na początku tury jednostki. Stackuje się. Główna mechanika ofensywna Stygian Guard.',
    examples: ['Flash Freeze', 'Icy Cilophyte', 'Frostbite spells'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Frostbite', verified: true,
  },
  'Harvest': {
    name: 'Harvest', game: 'Monster Train',
    short_desc: 'Efekt triggerowany gdy sojusznicza jednostka zginie na tym piętrze.',
    full_desc: 'Harvest triggeruje się gdy sojusznicza jednostka na tym samym piętrze umrze. Synergizuje z Burnout (Melting Remnant) — units z Burnout umierają regularnie, triggerując Harvest.',
    examples: ['Rector Flicker', 'Wickless Tycoon'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Harvest', verified: true,
  },
  'Inspire': {
    name: 'Inspire', game: 'Monster Train',
    short_desc: 'Daje buff wszystkim sojuszniczym jednostkom na piętrze.',
    full_desc: 'Inspire aplikuje efekt do wszystkich sojuszniczych jednostek na tym samym piętrze. Np. "Inspire: +5 Attack" daje +5 Attack wszystkim sojuszniczym units.',
    examples: ['Shardtail Queen'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Inspire', verified: true,
  },
  'Morsel': {
    name: 'Morsel', game: 'Monster Train',
    short_desc: 'Mała jednostka-jedzenie zjadana przez Gorge units.',
    full_desc: 'Morsele to małe jednorazowe units klanu Umbra. Gdy Morsel jest postawiony na piętrze z unitką z Gorge, jest automatycznie zjadany — triggerując efekt Gorge. Różne Morsele dają różne bonusy (Attack, Health, itp).',
    examples: ['Antumbra Morsel', 'Magma Morsel', 'Rubble Morsel'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Morsel', verified: true,
  },
  'Purge': {
    name: 'Purge', game: 'Monster Train',
    short_desc: 'Usuwa kartę z gry na stałe.',
    full_desc: 'Purge trwale usuwa kartę z talii — nie wraca. Silniejsze od Consume, bo karta znika na dobre. Przydatne do usuwania słabych kart.',
    examples: ['Purge spells'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Purge', verified: true,
  },
  'Quick': {
    name: 'Quick', game: 'Monster Train',
    short_desc: 'Jednostka atakuje PRZED wrogami na tym samym piętrze.',
    full_desc: 'Normalnie wrogowie atakują pierwsi. Quick odwraca kolejność — unit z Quick uderza zanim wrogowie zdążą zaatakować. Bardzo silny z Sweep — Quick+Sweep unit może wyeliminować całe piętro zanim wrogowie zareagują. Można uzyskać przez Speedstone upgrade.',
    examples: ['Animus of Speed', 'Little Fade', 'Wyldenten'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Quick', verified: true,
  },
  'Reform': {
    name: 'Reform', game: 'Monster Train',
    short_desc: 'Po śmierci jednostka wraca do ręki z powiększonymi statami.',
    full_desc: 'Reform zwraca jednostkę do ręki po śmierci, dodając bonusowe staty. Reform X dodaje +X/+X (Attack/Health). Kluczowa mechanika Melting Remnant — units z Burnout umierają, Reform je przywraca silniejsze.',
    examples: ['Rector Flicker', 'Formless Child', 'Wickless Baron'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Reform', verified: true,
  },
  'Regen': {
    name: 'Regen', game: 'Monster Train',
    short_desc: 'Leczy jednostkę na początku jej tury.',
    full_desc: 'Regen X leczy jednostkę o X HP na początku tury. Stackuje się.',
    examples: ['The Sentient', 'Regen spells'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Regen', verified: true,
  },
  'Rejuvenate': {
    name: 'Rejuvenate', game: 'Monster Train',
    short_desc: 'Leczy jednostkę o podaną wartość natychmiast.',
    full_desc: 'Rejuvenate leczy jednostkę natychmiast (nie na początku tury jak Regen). Jednorazowe leczenie.',
    examples: ['Rejuvenate spells'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Rejuvenate', verified: true,
  },
  'Resolve': {
    name: 'Resolve', game: 'Monster Train',
    short_desc: 'Efekt triggerowany na końcu tury.',
    full_desc: 'Resolve triggeruje się na końcu każdej tury walki. Automatyczny efekt powtarzalny. Podobny do pasywnych efektów co-turowych.',
    examples: ['Resolve units'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Resolve', verified: true,
  },
  'Sap': {
    name: 'Sap', game: 'Monster Train',
    short_desc: 'Debuff redukujący atak po każdym ataku wroga.',
    full_desc: 'Sap X zmniejsza Attack wroga o X po każdym jego ataku. Stackuje się — wielokrotne Sap szybko osłabia wrogów. Wiki potwierdza: reduces attack by the listed amount after attacking.',
    examples: ['Edge Prior', 'Tethys Titansbane'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Sap', verified: true,
  },
  'Spell Weakness': {
    name: 'Spell Weakness', game: 'Monster Train',
    short_desc: 'Cel otrzymuje podwójne obrażenia od spelli.',
    full_desc: 'Spell Weakness sprawia że cel otrzymuje podwójne obrażenia od zagranych spelli. Stackuje się — Spell Weakness 2 = 4x obrażenia od spelli.',
    examples: ['Siren of the Sea'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Spell_Weakness', verified: true,
  },
  'Spikes': {
    name: 'Spikes', game: 'Monster Train',
    short_desc: 'Zadaje obrażenia atakującemu.',
    full_desc: 'Spikes X zadaje X obrażeń każdemu wrogowi który zaatakuje tę jednostkę. Odpowiednik Thorns ze StS. Stackuje się.',
    examples: ['Spine Chief', 'Spikedriver Colony', 'Automatic Railspikes'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Spikes', verified: true,
  },
  'Stealth': {
    name: 'Stealth', game: 'Monster Train',
    short_desc: 'Jednostka nie może być zaatakowana przez wrogie units.',
    full_desc: 'Stealth zapobiega atakowaniu jednostki przez wrogów, włącznie z Sweep. Wiki: "It prevents a unit from being attacked by opposing units, including units with Sweep. It has no effect on non-attack damage, such as Triggers and damaging abilities." Jeśli Stealth unit stoi z przodu, wrogowie atakują jednostkę za nią.',
    examples: ['Little Fade', 'Bounty Stalker', 'Engulfed in Smoke'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Stealth', verified: true,
  },
  'Summon': {
    name: 'Summon', game: 'Monster Train',
    short_desc: 'Przywołanie nowej jednostki na piętro.',
    full_desc: 'Summon tworzy nową jednostkę na piętrze. Triggerowane gdy unit jest postawiony (Summon: efekt) lub jako efekt spella. Summoned units nie kosztują Ember.',
    examples: ['Morsel Miner', 'Demon Fiend', 'Alpha Fiend'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Summon', verified: true,
  },
  'Trample': {
    name: 'Trample', game: 'Monster Train',
    short_desc: 'Nadmiarowe obrażenia przechodzą na następną jednostkę.',
    full_desc: 'Trample sprawia że obrażenia które "przebiją" zabity unit przechodzą na następnego wroga w linii. Silny z wysoko-atakującymi unitami jak Overgorger.',
    examples: ['Overgorger'], wiki_url: 'https://monstertrain2.miraheze.org/wiki/Trample', verified: true,
  },
  // ── WF MISSING ──
  'Aimless': {
    name: 'Aimless', game: 'Wildfrost',
    short_desc: 'Atak trafia losowego wroga zamiast celowanego.',
    full_desc: 'Karta z Aimless nie atakuje wybranego celu — zamiast tego trafia losowego wroga. Mniejsza kontrola ale często silniejsze staty w zamian.',
    examples: ['Aimless companions'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Aimless', verified: true,
  },
  'Bom': {
    name: 'Bom', game: 'Wildfrost',
    short_desc: 'Eksploduje po odliczeniu countera, zadając obrażenia.',
    full_desc: 'Bom to efekt eksplozji — po odliczeniu countera karta eksploduje, zadając obrażenia wszystkim wrogom. Jednorazowy efekt.',
    examples: ['Bom items'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Bom', verified: true,
  },
  'Shroom': {
    name: 'Shroom', game: 'Wildfrost',
    short_desc: 'Debuff — po ataku wroga zadaje dodatkowe obrażenia.',
    full_desc: 'Shroom X zadaje X dodatkowych obrażeń po tym jak wróg zaatakuje. Potem Shroom jest zużywany. Typ obrażeń over-time triggerowany atakiem.',
    examples: ['Dregg'], wiki_url: 'https://wildfrost.wiki.gg/wiki/Shroom', verified: true,
  },
}
